.PHONY: vet
vet:
	go vet `$(GO_PACKAGES)`
	@echo ""

.PHONY: golangci-lint
golangci-lint: $(TOOLS_BIN)/golangci-lint
	golangci-lint run
	@echo ''

.PHONY: golangci-lint-fmt
golangci-lint-fmt: $(TOOLS_BIN)/golangci-lint
	golangci-lint fmt
	@echo ''

.PHONY: gofmt
gofmt:
	gofmt -w `$(GO_FILES)`

.PHONY: gofmt.display
gofmt.display:
	gofmt -d `$(GO_FILES)`

.PHONY: shfmt
shfmt: $(TOOLS_BIN)/shfmt
	./scripts/foreach-script $(TOOLS_BIN)/shfmt \
		--simplify \
		--language-dialect auto \
		--case-indent \
		--indent 2 \
		--write

.PHONY: shellcheck
shellcheck: $(TOOLS_BIN)/shellcheck
	./scripts/foreach-script $(TOOLS_BIN)/shellcheck \
		--norc \
		--external-sources \
		--format=tty \
		--enable=require-variable-braces,add-default-case

.PHONY: mockery
mockery: $(TOOLS_BIN)/mockery
	grep --recursive --files-with-matches '// Code generated by mockery' . | grep -v 'tools/tools.mk' | grep -v 'bin/mockery' | xargs rm || true
	mockery --config ./.mockery.yml
